### ISSUE TITLE
Create additional linguistic features

### ISSUE THREAD

**Issue by iangow** [iangow/ling_features#2]
@azakolyukina The following is a (partial) list from another (fog-focused) project. The tone measures could be calculated at the question level. But call-level features might be relevant predictors too.

The following variables are by "category" (i.e., analyst or company, presentation or Q&A):

`fog`is the Gunning (1958) fog index. The following are inputs to `fog = 0.4 * (percent_complex + num_words/num_sentences`.

* `num_words`: Number of words
* `percent_complex = 100 * num_complex_words/num_words`
* `num_sentences`: Number of sentences
* `num_complex_words`: Number of "complex" words (words with more than three syllables)

`num_jargon_words` is the number of three-syllable words in the respective portion of the call that are industry jargon, defined as the 100 most common three-syllable words used by firms in the industry based on two-digit SIC codes.

The following three call-category-level variables are a decomposition of fog (add them up to get fog):

* `fog_jargon`: Portion of the "percent_complex" component attributable to top 100 complex words by two-digit SIC code
* `fog_special`: Portion of the "percent_complex" component *not* attributable to top 100 complex words by two-digit SIC code
* `fog_words_sent`: Portion of fog related to words per sentence

`prop_fl_sents`: Proportion of sentences that are forward-looking

`word_count`: Word count using Python's Natural Language Toolkit (counts words differently from Perl module used for fog)

These call-category-level variables are from Loughran and McDonald (2014) and represent the number of words falling into each category:
`litigious`, `positive`, `uncertainty`, `negative`, `modal_strong`, `modal_weak`

The following variables are call-level variables based on within-call regressions:
`r_squared`, `num_obs`, `constant`, `slope`, `mean_analyst_fog`, `mean_manager_fog`

### References
- Li, F. (2010). The Information Content of Forward-Looking Statements in Corporate Filings—A Naïve Bayesian Machine Learning Approach. Journal of Accounting Research, 48(5), 1049–1102. 
- Loughran, T., & McDonald, B. (2014). Measuring Readability in Financial Disclosures. The Journal of Finance, 69(4), 1643–1671.

**Comment by azakolyukina** [comment]
> The following variables are call-level variables based on within-call regressions:
> r_squared, num_obs, constant, slope, mean_analyst_fog, mean_manager_fog

We should probably try everything else except for these.

**Comment by azakolyukina** [comment]
This code belongs to `bs_linguistics`. Moved to [bs_linguistics/#27](https://github.com/azakolyukina/bs_linguistics/issues/27)

**Comment by iangow** [comment]
This issue will mostly be addressed as https://github.com/azakolyukina/bs_linguistics/issues/48.
